[package]
name = "hello_egui"
version = "0.4.0"
edition = "2021"
description = "A collection of useful crates for egui."
authors = ["Lucas Meurer"]
license = "MIT"
repository = "https://github.com/lucasmerlin/hello_egui"
homepage = "https://lucasmerlin.github.io/hello_egui/"

[package.metadata.release]
tag-prefix = "hello_egui-"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
all = ["dnd", "inbox", "pull_to_refresh", "animation", "suspense", "virtual_list", "infinite_scroll", "thumbhash"]

dnd = ["dep:egui_dnd"]
inbox = ["dep:egui_inbox"]
pull_to_refresh = ["dep:egui_pull_to_refresh"]
animation = ["dep:egui_animation"]
suspense = ["dep:egui_suspense"]
virtual_list = ["dep:egui_virtual_list"]
infinite_scroll = ["dep:egui_infinite_scroll"]
thumbhash = ["dep:egui_thumbhash"]
async = ["egui_suspense/async", "egui_infinite_scroll/async"]
tokio = ["egui_suspense/tokio", "egui_infinite_scroll/tokio"]

[dependencies]
egui_dnd = { workspace = true, optional = true }
egui_inbox = { workspace = true, optional = true }
egui_pull_to_refresh = { workspace = true, optional = true }
egui_animation = { workspace = true, optional = true }
egui_suspense = { workspace = true, optional = true }
egui_virtual_list = { workspace = true, optional = true }
egui_infinite_scroll = { workspace = true, optional = true }
egui_thumbhash = { workspace = true, optional = true }


[workspace]
members = ["fancy-example", "crates/*", "scripts"]
resolver = "2"

[workspace.dependencies]
egui_dnd = { path = "./crates/egui_dnd", version = "0.8.0" }
egui_animation = { path = "./crates/egui_animation", version = "0.4.0" }
hello_egui_utils = { path = "./crates/hello_egui_utils", version = "0.4.0" }
egui_inbox = { path = "./crates/egui_inbox", version = "0.4.0" }
egui_pull_to_refresh = { path = "./crates/egui_pull_to_refresh", version = "0.4.0" }
egui_suspense = { path = "./crates/egui_suspense", version = "0.4.0" }
egui_virtual_list = { path = "./crates/egui_virtual_list", version = "0.3.0" }
egui_infinite_scroll = { path = "./crates/egui_infinite_scroll", version = "0.3.0" }
egui_thumbhash = { path = "./crates/egui_thumbhash", version = "0.3.0" }
hello_egui = { path = ".", version = "0.4.0" }

egui = { git = "https://github.com/RyanBluth/egui.git", branch = "main" }
eframe = { git = "https://github.com/RyanBluth/egui.git", branch = "main" }
egui_extras = { git = "https://github.com/RyanBluth/egui.git", branch = "main" }

[patch.crates-io]
#wry = { path = "../../RustroverProjects/github/wry" }
#
#egui = { path = "../../IdeaProjects/egui/crates/egui" }
#egui-wgpu = { path = "../../IdeaProjects/egui/crates/egui-wgpu" }
